version: '3.8'
services:
  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    container_name: cryb-pgbouncer
    restart: unless-stopped
    ports:
      - "6432:6432"
    environment:
      - DATABASES_HOST=172.17.0.1
      - DATABASES_PORT=5433
      - DATABASES_DBNAME=cryb
      - DATABASES_USER=cryb_user
      - DATABASES_PASSWORD=cryb_password
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=5000
      - DEFAULT_POOL_SIZE=25
      - MIN_POOL_SIZE=10
      - RESERVE_POOL_SIZE=10
      - SERVER_LIFETIME=3600
    network_mode: host