/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TokenGatingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessTimestamp"
      | "createGate"
      | "createRequirement"
      | "gates"
      | "getGateRequirements"
      | "grantAccess"
      | "hasAccess"
      | "meetsRequirement"
      | "nextGateId"
      | "nextRequirementId"
      | "owner"
      | "renounceOwnership"
      | "requirements"
      | "revokeAccess"
      | "setGateActive"
      | "setRequirementActive"
      | "transferOwnership"
      | "userAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "GateCreated"
      | "OwnershipTransferred"
      | "RequirementCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessTimestamp",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGate",
    values: [string, string, BigNumberish[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "createRequirement",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "gates", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getGateRequirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "meetsRequirement",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextGateId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequirementId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGateActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequirementActive",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userAccess",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "accessTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGateRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "meetsRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextGateId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRequirementId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGateActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequirementActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userAccess", data: BytesLike): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [gateId: BigNumberish, user: AddressLike];
  export type OutputTuple = [gateId: bigint, user: string];
  export interface OutputObject {
    gateId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [gateId: BigNumberish, user: AddressLike];
  export type OutputTuple = [gateId: bigint, user: string];
  export interface OutputObject {
    gateId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GateCreatedEvent {
  export type InputTuple = [gateId: BigNumberish, name: string];
  export type OutputTuple = [gateId: bigint, name: string];
  export interface OutputObject {
    gateId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequirementCreatedEvent {
  export type InputTuple = [
    requirementId: BigNumberish,
    tokenAddress: AddressLike,
    minAmount: BigNumberish,
    isNFT: boolean
  ];
  export type OutputTuple = [
    requirementId: bigint,
    tokenAddress: string,
    minAmount: bigint,
    isNFT: boolean
  ];
  export interface OutputObject {
    requirementId: bigint;
    tokenAddress: string;
    minAmount: bigint;
    isNFT: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenGating extends BaseContract {
  connect(runner?: ContractRunner | null): TokenGating;
  waitForDeployment(): Promise<this>;

  interface: TokenGatingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessTimestamp: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  createGate: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _requirementIds: BigNumberish[],
      _requireAll: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  createRequirement: TypedContractMethod<
    [_tokenAddress: AddressLike, _minAmount: BigNumberish, _isNFT: boolean],
    [bigint],
    "nonpayable"
  >;

  gates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, bigint] & {
        name: string;
        description: string;
        requireAll: boolean;
        isActive: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;

  getGateRequirements: TypedContractMethod<
    [_gateId: BigNumberish],
    [bigint[]],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  meetsRequirement: TypedContractMethod<
    [_requirementId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;

  nextGateId: TypedContractMethod<[], [bigint], "view">;

  nextRequirementId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requirements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean] & {
        tokenAddress: string;
        minAmount: bigint;
        isNFT: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;

  revokeAccess: TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;

  setGateActive: TypedContractMethod<
    [_gateId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  setRequirementActive: TypedContractMethod<
    [_requirementId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userAccess: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessTimestamp"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createGate"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _requirementIds: BigNumberish[],
      _requireAll: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRequirement"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _minAmount: BigNumberish, _isNFT: boolean],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, boolean, bigint] & {
        name: string;
        description: string;
        requireAll: boolean;
        isActive: boolean;
        accessCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGateRequirements"
  ): TypedContractMethod<[_gateId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "meetsRequirement"
  ): TypedContractMethod<
    [_requirementId: BigNumberish, _user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextGateId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextRequirementId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requirements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean, boolean] & {
        tokenAddress: string;
        minAmount: bigint;
        isNFT: boolean;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [_gateId: BigNumberish, _user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGateActive"
  ): TypedContractMethod<
    [_gateId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRequirementActive"
  ): TypedContractMethod<
    [_requirementId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userAccess"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "GateCreated"
  ): TypedContractEvent<
    GateCreatedEvent.InputTuple,
    GateCreatedEvent.OutputTuple,
    GateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequirementCreated"
  ): TypedContractEvent<
    RequirementCreatedEvent.InputTuple,
    RequirementCreatedEvent.OutputTuple,
    RequirementCreatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,address)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(uint256,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "GateCreated(uint256,string)": TypedContractEvent<
      GateCreatedEvent.InputTuple,
      GateCreatedEvent.OutputTuple,
      GateCreatedEvent.OutputObject
    >;
    GateCreated: TypedContractEvent<
      GateCreatedEvent.InputTuple,
      GateCreatedEvent.OutputTuple,
      GateCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequirementCreated(uint256,address,uint256,bool)": TypedContractEvent<
      RequirementCreatedEvent.InputTuple,
      RequirementCreatedEvent.OutputTuple,
      RequirementCreatedEvent.OutputObject
    >;
    RequirementCreated: TypedContractEvent<
      RequirementCreatedEvent.InputTuple,
      RequirementCreatedEvent.OutputTuple,
      RequirementCreatedEvent.OutputObject
    >;
  };
}
