# CRYB Platform Production PostgreSQL Cluster Configuration
# High-availability setup with primary/replica architecture for Reddit/Discord scale
# Author: Database Infrastructure Team
# Version: 1.0

version: '3.9'

services:
  # ==========================================
  # PRIMARY DATABASE SERVER
  # ==========================================
  postgres-primary:
    image: timescale/timescaledb:latest-pg15
    container_name: cryb-postgres-primary
    hostname: postgres-primary
    restart: unless-stopped
    
    environment:
      # Core PostgreSQL configuration
      POSTGRES_DB: cryb
      POSTGRES_USER: cryb_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "-E UTF8"
      
      # Replication configuration
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      
      # TimescaleDB configuration
      TIMESCALEDB_TELEMETRY: off
      
    ports:
      - "5432:5432"
      
    volumes:
      # Data persistence
      - postgres_primary_data:/var/lib/postgresql/data
      
      # Configuration files
      - ./config/postgres/postgresql-primary.conf:/etc/postgresql/postgresql.conf
      - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      
      # Initialization scripts
      - ./database/enhanced-production-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/timescaledb-analytics-setup.sql:/docker-entrypoint-initdb.d/02-timescaledb.sql
      - ./database/performance-optimization.sql:/docker-entrypoint-initdb.d/03-optimization.sql
      - ./database/replication-setup.sql:/docker-entrypoint-initdb.d/04-replication.sql
      
      # WAL archiving
      - postgres_wal_archive:/var/lib/postgresql/wal_archive
      
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryb_user -d cryb -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
      
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
          
    labels:
      - "com.cryb.service=postgres-primary"
      - "com.cryb.role=database"
      - "com.cryb.tier=primary"

  # ==========================================
  # READ REPLICA DATABASE SERVERS
  # ==========================================
  postgres-replica-1:
    image: timescale/timescaledb:latest-pg15
    container_name: cryb-postgres-replica-1
    hostname: postgres-replica-1
    restart: unless-stopped
    
    environment:
      # Replica configuration
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PRIMARY_HOST: postgres-primary
      POSTGRES_PRIMARY_PORT: 5432
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      POSTGRES_DB: cryb
      
    ports:
      - "5433:5432"
      
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
      - ./config/postgres/postgresql-replica.conf:/etc/postgresql/postgresql.conf
      - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts/setup-replica.sh:/docker-entrypoint-initdb.d/setup-replica.sh
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
      
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3.0'
        reservations:
          memory: 3G
          cpus: '1.5'
          
    labels:
      - "com.cryb.service=postgres-replica"
      - "com.cryb.role=database"
      - "com.cryb.tier=replica"

  postgres-replica-2:
    image: timescale/timescaledb:latest-pg15
    container_name: cryb-postgres-replica-2
    hostname: postgres-replica-2
    restart: unless-stopped
    
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PRIMARY_HOST: postgres-primary
      POSTGRES_PRIMARY_PORT: 5432
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
      POSTGRES_DB: cryb
      
    ports:
      - "5434:5432"
      
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
      - ./config/postgres/postgresql-replica.conf:/etc/postgresql/postgresql.conf
      - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./scripts/setup-replica.sh:/docker-entrypoint-initdb.d/setup-replica.sh
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s
      
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3.0'
        reservations:
          memory: 3G
          cpus: '1.5'
          
    labels:
      - "com.cryb.service=postgres-replica"
      - "com.cryb.role=database" 
      - "com.cryb.tier=replica"

  # ==========================================
  # PGBOUNCER CONNECTION POOLING
  # ==========================================
  pgbouncer-primary:
    image: pgbouncer/pgbouncer:latest
    container_name: cryb-pgbouncer-primary
    hostname: pgbouncer-primary
    restart: unless-stopped
    
    environment:
      DATABASES_HOST: postgres-primary
      DATABASES_PORT: 5432
      DATABASES_USER: cryb_user
      DATABASES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASES_DBNAME: cryb
      POOL_MODE: transaction
      LISTEN_PORT: 6432
      MAX_CLIENT_CONN: 2000
      DEFAULT_POOL_SIZE: 50
      MIN_POOL_SIZE: 10
      RESERVE_POOL_SIZE: 10
      MAX_DB_CONNECTIONS: 100
      
    ports:
      - "6432:6432"
      
    volumes:
      - ./config/pgbouncer/pgbouncer-primary.ini:/etc/pgbouncer/pgbouncer.ini
      - ./config/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-p", "6432", "-U", "cryb_user", "-d", "cryb", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  pgbouncer-readonly:
    image: pgbouncer/pgbouncer:latest
    container_name: cryb-pgbouncer-readonly
    hostname: pgbouncer-readonly
    restart: unless-stopped
    
    environment:
      DATABASES_HOST: postgres-replica-1,postgres-replica-2
      DATABASES_PORT: 5432
      DATABASES_USER: cryb_user
      DATABASES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASES_DBNAME: cryb
      POOL_MODE: transaction
      LISTEN_PORT: 6432
      MAX_CLIENT_CONN: 1500
      DEFAULT_POOL_SIZE: 40
      MIN_POOL_SIZE: 8
      RESERVE_POOL_SIZE: 8
      MAX_DB_CONNECTIONS: 80
      
    ports:
      - "6433:6432"
      
    volumes:
      - ./config/pgbouncer/pgbouncer-readonly.ini:/etc/pgbouncer/pgbouncer.ini
      - ./config/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
      
    depends_on:
      postgres-replica-1:
        condition: service_healthy
      postgres-replica-2:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-p", "6432", "-U", "cryb_user", "-d", "cryb", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # ==========================================
  # DATABASE MONITORING AND METRICS
  # ==========================================
  postgres-exporter-primary:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: cryb-postgres-exporter-primary
    restart: unless-stopped
    
    environment:
      DATA_SOURCE_NAME: "postgresql://cryb_monitoring:${MONITORING_PASSWORD}@postgres-primary:5432/cryb?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
      
    ports:
      - "9187:9187"
      
    volumes:
      - ./config/postgres-exporter/queries.yaml:/etc/postgres-exporter/queries.yaml
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  postgres-exporter-replica:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: cryb-postgres-exporter-replica
    restart: unless-stopped
    
    environment:
      DATA_SOURCE_NAME: "postgresql://cryb_monitoring:${MONITORING_PASSWORD}@postgres-replica-1:5432/cryb?sslmode=disable"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres-exporter/queries.yaml"
      
    ports:
      - "9188:9187"
      
    volumes:
      - ./config/postgres-exporter/queries.yaml:/etc/postgres-exporter/queries.yaml
      
    depends_on:
      postgres-replica-1:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  # ==========================================
  # PGPOOL-II FOR LOAD BALANCING
  # ==========================================
  pgpool:
    image: pgpool/pgpool:4.4
    container_name: cryb-pgpool
    hostname: pgpool
    restart: unless-stopped
    
    environment:
      PGPOOL_BACKEND_NODES: "0:postgres-primary:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:postgres-replica-1:5432:1:/var/lib/postgresql/data:DISALLOW_TO_FAILOVER,2:postgres-replica-2:5432:1:/var/lib/postgresql/data:DISALLOW_TO_FAILOVER"
      PGPOOL_SR_CHECK_USER: replicator
      PGPOOL_SR_CHECK_PASSWORD: ${REPLICATION_PASSWORD}
      PGPOOL_POSTGRES_USERNAME: cryb_user
      PGPOOL_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPOOL_ADMIN_USERNAME: admin
      PGPOOL_ADMIN_PASSWORD: ${PGPOOL_ADMIN_PASSWORD}
      PGPOOL_ENABLE_LDAP: "no"
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_MAX_POOL: 4
      PGPOOL_CHILD_LIFE_TIME: 300
      PGPOOL_CHILD_MAX_CONNECTIONS: 100
      PGPOOL_CONNECTION_LIFE_TIME: 600
      PGPOOL_CLIENT_IDLE_LIMIT: 0
      
    ports:
      - "5435:5432"  # Main connection pool
      - "9999:9999"  # PCP port for administration
      
    volumes:
      - ./config/pgpool/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
      - ./config/pgpool/pool_hba.conf:/opt/bitnami/pgpool/conf/pool_hba.conf
      
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica-1:
        condition: service_healthy
      postgres-replica-2:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD", "/opt/bitnami/pgpool/bin/pg_isready", "-h", "localhost", "-p", "5432", "-U", "cryb_user", "-d", "cryb"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # ==========================================
  # DATABASE BACKUP SERVICE
  # ==========================================
  postgres-backup:
    image: prodrigestivill/postgres-backup-local:15
    container_name: cryb-postgres-backup
    restart: unless-stopped
    
    environment:
      POSTGRES_HOST: postgres-primary
      POSTGRES_DB: cryb
      POSTGRES_USER: cryb_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTRA_OPTS: "--verbose --clean --if-exists"
      SCHEDULE: "0 2 * * *"  # Daily at 2 AM
      BACKUP_KEEP_DAYS: 30
      BACKUP_KEEP_WEEKS: 8
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
      
    volumes:
      - postgres_backups:/backups
      - ./scripts/backup-hooks:/hooks
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ==========================================
  # WAL-G FOR CONTINUOUS ARCHIVING
  # ==========================================
  wal-g-backup:
    image: wal-g/wal-g:latest
    container_name: cryb-wal-g-backup
    restart: unless-stopped
    
    environment:
      WALG_S3_PREFIX: "s3://${BACKUP_BUCKET}/postgres-wal"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      PGHOST: postgres-primary
      PGPORT: 5432
      PGUSER: cryb_user
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: cryb
      WALG_COMPRESSION_METHOD: brotli
      WALG_DELTA_MAX_STEPS: 7
      
    volumes:
      - postgres_wal_archive:/var/lib/postgresql/wal_archive:ro
      - ./scripts/wal-g-scripts:/scripts
      
    depends_on:
      postgres-primary:
        condition: service_healthy
        
    networks:
      - cryb-cluster-network
      
    command: >
      sh -c "
        # Create base backup
        wal-g backup-push /var/lib/postgresql/data
        
        # Monitor and archive WAL files
        while true; do
          sleep 300
          wal-g backup-list
        done
      "

# ==========================================
# NETWORKS AND VOLUMES
# ==========================================
networks:
  cryb-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  # Primary database data
  postgres_primary_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryb/postgres/primary
      
  # Replica database data
  postgres_replica1_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryb/postgres/replica1
      
  postgres_replica2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryb/postgres/replica2
      
  # WAL archiving
  postgres_wal_archive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryb/postgres/wal_archive
      
  # Backup storage
  postgres_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/cryb/backups/postgres